MODEL:
  PRETRAIN_CHOICE: 'imagenet' # imagenet
  PRETRAIN_PATH: "/home/nihao/data/checkpoints" # root of pretrain path
  METRIC_LOSS_TYPE: 'triplet' # triplet, triplet_center
  DIM: 768
  IF_LABELSMOOTH: 'on'
  NAME: 'mix_vit' # local_attention_vit, mask_vit, mae, DG_ssl_vit, color_vit, rotate_vit, resnet50, ibnnet50, vit, distill_vit, prompt_vit, mix_vit, mem_vit
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID' # vit_large_patch16_224_TransReID, vit_base_patch16_224_TransReID, vit_base_patch32_224_TransReID, deit_base_patch16_224_TransReID, vit_small_patch16_224_TransReID, deit_small_patch16_224_TransReID, deit_tiny_patch16_224_TransReID, swin_base_patch4_window7_224, swin_small_patch4_window7_224, dhvt_tiny_patch16, dhvt_small_patch16
  STRIDE_SIZE: 16
  DROP_PATH: 0.1 ###### avoid overfitting
  # FREEZE_PATCH_EMBED: True
  # FIXED_RES_BN: True
  NORM:
    TYPE: 'LN'

############ DISTILL settings ############
  DISTILL:
    # DO_XDED: True
    # DO_DISTILL: True
    LAMBDA: 0.2
    NUM_SELECT_BLOCK: 1
    START_EPOCH: 1
    LOSS_TYPE: 'EUC'
    IF_HEAD: False
    IF_DEEP_SUPERVISE: False
############ DISTILL settings ############

############decoder settings############
  DECODER:
    DIM: 384
    DEPTH: 4
    NUM_HEAD: 8
    MLP_RATIO: 4.
    NORM: 'LN'
############decoder settings############


# #################pc loss#################
  PC_LOSS: True
  PC_SCALE: 0.001
  PC_LR: 0.1 ######################## try this

  PART_NUM: 3

  CLUSTER_K: 10
# #################pc loss#################

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  # LGT: # Local Grayscale Transfomation
  #   DO_LGT: True
  #   PROB: 0.5

DATASETS:
  # TRAIN: ('Market1501',)
  TRAIN: ('DG_Market1501', 'DG_CUHK02', 'DG_CUHK03_detected', 'DG_CUHK_SYSU',) # multi
  # TRAIN: ("DukeMTMC", "MSMT17", "Market1501", "CUHK03")
  # TRAIN: ('DG_Market1501', 'DG_CUHK02', 'DG_CUHK03_labeled', 'DG_CUHK_SYSU',)
  # TRAIN: ('PACS',)
  # TEST: ('DukeMTMC',)
  # TEST: ("DukeMTMC", "CUHK03", "Market1501", "MSMT17") # DukeMTMC
  TEST: ("DG_GRID", "DG_VIPeR", "DG_PRID", "DG_iLIDS", ) # multi
  ROOT_DIR: ('/home/nihao/data') # root of datasets
  # COMBINEALL: True
  TEST_ALL: False

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  CAMERA_TO_DOMAIN: True
  RANDOM_BATCH: False ## Default True; False: only one domain for a batch

SOLVER:
  OPTIMIZER_NAME: 'SGD' # AdamW
  # OPTIMIZER_NAME: 'SAM'
  MAX_EPOCHS: 60
  BASE_LR: 0.001 # 0.0004 for msmt
  IMS_PER_BATCH: 64
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 60 ## 60
  EVAL_PERIOD: 5
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  SEED: 1234

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  # WEIGHT: '/home/nihao/data/exp/vit_multi_clssifier_test/multi-source/vit_best.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: True

LOG_ROOT: '/home/nihao/data/exp/' # root of log file
TB_LOG_ROOT: './tb_log/'
# LOG_NAME: 'vit_center_loss'
# LOG_NAME: 'vit_hint_euc_0.2_1block/multi_source'
# LOG_NAME: 'vit_hint_euc_0.2_1block_fix_PE'
# LOG_NAME: 'debug'
# LOG_NAME: 'prompt_vit/domain_prompts/noparam_for_prompt_tokens/multi_source'
# LOG_NAME: 'prompt_vit/domain_prompts/domain_tokens_to_domain_predict'
# LOG_NAME: 'vit_mixstyle_3_substitute/multi_source'
# LOG_NAME: 'vit_mixstyle_efdmix_XDED_center/multi-source'
# LOG_NAME: 'ibnnet_b101/MS+D+C_ALL_to_M'
# LOG_NAME: 'XDED_vit/bs=64/tao1lam0.2'
# LOG_NAME: 'vit_M3L_memory_class_temp15/multi-source'
# LOG_NAME: 'vit_multi_clssifier_test/multi-source'
# LOG_NAME: 'vit_domainqueue_3_mixstylelike_domain_shuffle/multi_source'
# LOG_NAME: 'vit_domainqueue3_domainshuffle/Market'
LOG_NAME: 'vit_single_domain_for_batches_domainqueue_new_3/multi_source'
